
line_width: 100

tab_size: 2
use_tabchars: false

dangle_parens: false
max_subargs_per_line: 3
separate_ctrl_name_with_space: true
separate_fn_name_with_space: false

enable_sort: true
autosort: true

command_case: lower
