
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        informational: true
    patch:
      default:
        target: 100%
        threshold: 0.5%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default

