name: C++ tests

# The workflow gets triggered by pushes and pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    # Checks out the code in the repository
    - uses: actions/checkout@v3

    - name: Install doctest
      run: |
        sudo apt-get install -y doctest
    # Sets up Python on the machine with the right version
    - name: Compile and run the C++ tests
      run: |
        cd ./CLUEstering/include/test/ && make
        ./run_tests.sh

