name: Pylint

# The workflow gets triggered by pushes and pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # install libraries used throughout the project
        # needed otherwise pylint gives import-errors
        pip install numpy matplotlib pandas scikit-learn pytest
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=8. $(git ls-files '*.py')
