
name: Test serial installation without boost preinstalled

# The workflow gets triggered by pushes and pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        submodules: true

    - name: Package the library inside a tarball
      working-directory: ${{github.workspace}}
      run: |
        ./packaging.sh

    - name: Pull Docker image from Docker Hub
      working-directory: ${{github.workspace}}
      run: docker pull sbalducci00/sbaldu:cluestering_arch.serial

    - name: Run commands inside Docker container
      working-directory: ${{github.workspace}}
      run: |
        docker run -v $(pwd)/dist:/app -w /app \
        sbalducci00/sbaldu:cluestering_arch.serial bash -c '
          tar -xvf CLUEstering*.tar.gz
          rm *.tar.gz
          cd CLUEstering*
          pip install .
        '

    - name: Check number of modules
      working-directory: ${{github.workspace}}/dist
      run: |
        cd CLUEstering*
        echo $PWD
        ls 
        echo ' '
        ls build/lib/CLUEstering/lib
        ls -l build/lib/CLUEstering/lib | wc -l > output.txt
        n_modules=$(cat output.txt)
        echo $n_modules
        if [[ $n_modules == 2 ]]
        then
          echo "Correct: Both and only the convolutional and serial modules are generated"
        else
          echo "Error: The number of modules generated is incorrect"
          exit 1
        fi
