name: Test debug compilation to check presence of warnings

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt install -y libboost-dev

    - name: Compile the tests in debug mode
      working-directory: ${{ github.workspace }}/tests
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build

