name: Upload the logs of the profiler as artifacts

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    # pull docker images for building and profiling
    - name: Pull docker images from DockerHub
      run: |
        docker pull sbalducci00/sbaldu:cluestering_arch.serial
        docker pull sbalducci00/sbaldu:profiler

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        docker run -v $(pwd):/app -w /app/profiling \
        sbalducci00/sbaldu:cluestering_arch.serial bash -c '
          cmake -B build && make -C build
        '

    - name: Profile
      working-directory: ${{github.workspace}}/profiling
      run: |
        docker run -v $(pwd):/app -w /app/profiling \
        sbalducci00/sbaldu:profiler bash -c '
          ./build/serial.out
          mkdir -p logs
          gprof -b ./build/serial.out > logs/test.log
        '

    - name: Archive log files
      uses: actions/upload-artifact@v4
      with:
        name: PR_${{ github.event.pull_request.number }}
        path: |
          profiling/logs/test.log
